package com.marketstock.sebiapplication;


import java.util.HashMap;

import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.ImageButton;
import android.widget.TextView;

import com.actionbarsherlock.app.ActionBar;
import com.actionbarsherlock.app.SherlockActivity;

public class Interpret_Report extends SherlockActivity {
	
	int index=1;
	TextView heading;
	TextView interpret;
	ImageButton next_button;
	ImageButton prev_button;
	HashMap<Integer, String> map3;
	HashMap<Integer, String> map4;
	@Override
    public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.interpret_report);
		ActionBar actionBar=getSupportActionBar();
		actionBar.setHomeButtonEnabled(true);
		actionBar.setDisplayHomeAsUpEnabled(true);
		heading = (TextView) findViewById(R.id.heading);
		interpret = (TextView) findViewById(R.id.interpretation);
		next_button = (ImageButton) findViewById(R.id.nextarrow);
		prev_button = (ImageButton) findViewById(R.id.prevarrow);
		
		String title1 = "Net Sales";
		String title2 = "Net Profit";
		String title3 = "Other Income";
		String title4 = "Debt/Equity Ratio";
		
		String netsales = " You should compare the Net Sales during the last quarter with the Net Sales during the same quarter in the previous year. For example, if you are looking for sales in Mar ‘13 then you should compare it with sales in Mar ‘12 to have an idea about how the company performed during the same quarter a year back.";
		String netprofit = "Just like Net Sales, you should compare net profit too.";
		String income =  "Other Income is the income generated by non-operational activities. For example if a company sells some of its ‘land’ while its core business is telecom. The land sale will be counted as Other Income. You should always deduct Other Income from Net Profit to know how much the company actually earned from operations.";
		String de_ratio = "You might not find this in financial report but you must always check how much loan a company has taken. Debt/Equity ratio of 1 to 3 might be fine depending upon the industry but still you must avoid a company with huge debt because the interest paid on the debt eats into the profit and the company might suffer due to this.";
		
		map3 = new HashMap<Integer, String>();
		map4 = new HashMap<Integer, String>();
		
		map4.put(1, netsales);
		map4.put(2, netprofit);
		map4.put(3, income);
		map4.put(4, de_ratio);
		
		map3.put(1, title1);
		map3.put(2, title2);
		map3.put(3, title3);
		map3.put(4, title4);
		
		heading.setText(map3.get(index));
		interpret.setText(map4.get(index));
		check_index(index);
		prev_button.setOnClickListener(new OnClickListener() {
			
			@Override
			public void onClick(View v) {
				index--;
				check_index(index);
				heading.setText(map3.get(index));
				interpret.setText(map4.get(index));
			}
		});
		
		next_button.setOnClickListener(new OnClickListener() {
					
					@Override
					public void onClick(View v) {
						index++;
						check_index(index);
						heading.setText(map3.get(index));
						interpret.setText(map4.get(index));
					}
				});
		 
		
	}
	
	public void check_index(int index)
	{
		if(index==1)
		{
			prev_button.setVisibility(View.INVISIBLE);
		}
		else if(index==4)
		{
			next_button.setVisibility(View.INVISIBLE);
		}
		else
		{
			next_button.setVisibility(View.VISIBLE);
			prev_button.setVisibility(View.VISIBLE);
		}
	}
	
}
